import { Manrope } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700"],
});

const generalSans = localFont({
  src: "../../public/fonts/GeneralSans-Regular.woff2",
  variable: "--font-general-sans",
});

export const metadata = {
  title: "Ena Ema Technologies",
  description: "Generated by Eftajul Islam Shadi for Ena Ema Technologies",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${generalSans.variable}`}>
        {children}

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
